function create_table( conn_to_database, table_name )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
    curs = exec(conn_to_database, ['CREATE TABLE IF NOT EXISTS ' table_name '('...
                      'SYMBOL TEXT,'...
                      'DATE   INTEGER,'...
                      'OPEN   INTEGER,'...
                      'HIGH   INTEGER,'...
                      'LOW    INTEGER,'...
                      'CLOSE  INTEGER,'...
                      'VOLUME INTEGER);']);
    close(curs);
end
