CREATE TABLE STOCK(SYMBOL TEXT,DATE   INTEGER,OPEN   REAL,HIGH   REAL,LOW    REAL,CLOSE  REAL,VOLUME INTEGER);
CREATE TABLE TEMP(SYMBOL TEXT,DATE   INTEGER,OPEN   REAL,HIGH   REAL,LOW    REAL,CLOSE  REAL,VOLUME INTEGER);
