CREATE TABLE TEMP (
symbol text unique,
open   integer);
CREATE TABLE STOCK(SYMBOL TEXT,DATE   INTEGER,OPEN   REAL,HIGH   REAL,LOW    REAL,CLOSE  REAL,VOLUME INTEGER,SYMBOL_DATE TEXT UNIQUE);
CREATE TABLE HOSE_STOCK_DIFF(SYMBOL                      TEXT,DATE                        INTEGER,CLOSE_DIFF                  REAL,CLOSE_DIFF_PERCENTAGE       REAL,OPEN_CLOSE_DIFF             REAL,OPEN_CLOSE_DIFF_PERCENTAGE  REAL,VOLUME_DIFF                 INTEGER,VOLUME_DIFF_PERCENTAGE      REAL,SYMBOL_DATE                 TEXT UNIQUE);
